// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'domain/emergent_stock.dart';
import 'domain/generic_name.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 719655758472596716),
    name: 'EmergentStock',
    lastPropertyId: const obx_int.IdUid(6, 2203949605880516998),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 442458135210748871),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5442330859297506240),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4309955984893075315),
        name: 'count',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 9057342834848722817),
        name: 'genericName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2203949605880516998),
        name: 'strength',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 1250713792628638593),
    name: 'GenericName',
    lastPropertyId: const obx_int.IdUid(2, 3565549724810644893),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5762215920622495187),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3565549724810644893),
        name: 'name',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(4, 1250713792628638593),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [3014334432606656959, 2387716134325941887],
    retiredIndexUids: const [],
    retiredPropertyUids: const [
      6185507381703655025,
      1240324940888893529,
      7515357026937317766,
      241676766436747577,
      8504567886132177154,
      7644121803486665283,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    EmergentStock: obx_int.EntityDefinition<EmergentStock>(
      model: _entities[0],
      toOneRelations: (EmergentStock object) => [],
      toManyRelations: (EmergentStock object) => {},
      getId: (EmergentStock object) => object.id,
      setId: (EmergentStock object, int id) {
        object.id = id;
      },
      objectToFB: (EmergentStock object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final genericNameOffset = fbb.writeString(object.genericName);
        final strengthOffset = fbb.writeString(object.strength);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addInt64(2, object.count);
        fbb.addOffset(4, genericNameOffset);
        fbb.addOffset(5, strengthOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = EmergentStock()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..name = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..count = const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0)
          ..genericName = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 12, '')
          ..strength = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 14, '');

        return object;
      },
    ),
    GenericName: obx_int.EntityDefinition<GenericName>(
      model: _entities[1],
      toOneRelations: (GenericName object) => [],
      toManyRelations: (GenericName object) => {},
      getId: (GenericName object) => object.id,
      setId: (GenericName object, int id) {
        object.id = id;
      },
      objectToFB: (GenericName object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        fbb.startTable(3);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = GenericName()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..name = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '');

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [EmergentStock] entity fields to define ObjectBox queries.
class EmergentStock_ {
  /// See [EmergentStock.id].
  static final id = obx.QueryIntegerProperty<EmergentStock>(
    _entities[0].properties[0],
  );

  /// See [EmergentStock.name].
  static final name = obx.QueryStringProperty<EmergentStock>(
    _entities[0].properties[1],
  );

  /// See [EmergentStock.count].
  static final count = obx.QueryIntegerProperty<EmergentStock>(
    _entities[0].properties[2],
  );

  /// See [EmergentStock.genericName].
  static final genericName = obx.QueryStringProperty<EmergentStock>(
    _entities[0].properties[3],
  );

  /// See [EmergentStock.strength].
  static final strength = obx.QueryStringProperty<EmergentStock>(
    _entities[0].properties[4],
  );
}

/// [GenericName] entity fields to define ObjectBox queries.
class GenericName_ {
  /// See [GenericName.id].
  static final id = obx.QueryIntegerProperty<GenericName>(
    _entities[1].properties[0],
  );

  /// See [GenericName.name].
  static final name = obx.QueryStringProperty<GenericName>(
    _entities[1].properties[1],
  );
}
